config/routes.rb
Rails.application.routes.draw do
  resources :recipes_lists do
    resources :todo_items
  end
  namespace :recipes_list do
    resources :todo_items
  end

  root "recipes_lists#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipes_list.rb
class RecipesList < ApplicationRecord
  has_many :todo_items

  def percent_complete
    return 0 if total_items == 0
    return ( 100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end

  def status
    case percent_complete.to_i
    when 0
      'Non commencée'
    when 100
      'Terminée'
    else 
      'En cours'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'info'
    else 
      'primary'
    end

  end

end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :recipes_list

  scope :completed, -> do
  where(completed: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_lists_controller.rb
class RecipesListsController < ApplicationController
  before_action :set_recipes_list, only: %i[ show edit update destroy ]

  # GET /recipes_lists or /recipes_lists.json
  def index
    @recipes_lists = RecipesList.all
  end

  # GET /recipes_lists/1 or /recipes_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /recipes_lists/new
  def new
    @recipes_list = RecipesList.new
  end

  # GET /recipes_lists/1/edit
  def edit
  end

  # POST /recipes_lists or /recipes_lists.json
  def create
    @recipes_list = RecipesList.new(recipes_list_params)

    respond_to do |format|
      if @recipes_list.save
        format.html { redirect_to @recipes_list, notice: "Recipes list was successfully created." }
        format.json { render :show, status: :created, location: @recipes_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipes_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes_lists/1 or /recipes_lists/1.json
  def update
    respond_to do |format|
      if @recipes_list.update(recipes_list_params)
        format.html { redirect_to @recipes_list, notice: "Recipes list was successfully updated." }
        format.json { render :show, status: :ok, location: @recipes_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipes_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes_lists/1 or /recipes_lists/1.json
  def destroy
    @recipes_list.destroy
    respond_to do |format|
      format.html { redirect_to recipes_lists_url, notice: "Recipes list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipes_list
      @recipes_list = RecipesList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipes_list_params
      params.require(:recipes_list).permit(:title)
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_recipes_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET recipes_lists/1/todo_items
  def index
    @todo_items = @recipes_list.todo_items
  end

  # GET recipes_lists/1/todo_items/1
  def show
  end

  # GET recipes_lists/1/todo_items/new
  def new
    @todo_item = @recipes_list.todo_items.build
  end

  # GET recipes_lists/1/todo_items/1/edit
  def edit
  end

  # POST recipes_lists/1/todo_items
  def create
    @todo_item = @recipes_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.recipes_list)
    else
      render action: 'new'
    end
  end

  # PUT recipes_lists/1/todo_items/1
  def update
    if @todo_item.update(todo_item_params)
      redirect_to([@todo_item.recipes_list, @todo_item], notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE recipes_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to recipes_list_todo_items_url(@recipes_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipes_list
      @recipes_list = RecipesList.find(params[:recipes_list_id])
    end

    def set_todo_item
      @todo_item = @recipes_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :completed_at, :recipes_list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_lists_helper.rb
module RecipesListsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookieOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2ec2a30cc1.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light'>
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <p id="notice"><%= notice %></p>
          <div class="card mt-5">
          <%= yield %>
          </div>
        </div>
      </div>
    </div>

  
  </body>
</html>

app/views/recipes_lists/_form.html.erb
<%= form_with(model: recipes_list) do |form| %>
  <% if recipes_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipes_list.errors.count, "error") %> prohibited this recipes_list from being saved:</h2>

      <ul>
        <% recipes_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes_lists/edit.html.erb
<h1>Editing Recipes List</h1>

<%= render 'form', recipes_list: @recipes_list %>

<%= link_to 'Show', @recipes_list %> |
<%= link_to 'Back', recipes_lists_path %>

app/views/recipes_lists/index.html.erb
<div class="card-header d-flex justify-content-between">
  <span>
    Liste des recettes
  </span>
 
  <%= link_to 'Nouvelle recette', new_recipes_list_path, class: 'btn btn-primary btn-sm' %>
</div>

<ul class='list-group'>
  <% @recipes_lists.each do |recipes_list| %>
    <li class='list-group-item'>
      <%= link_to recipes_list.title, recipes_list %>
    </li>
  <% end %>
</ul>

app/views/recipes_lists/new.html.erb
<h1>Nouvelle recette</h1>

<%= render 'form', recipes_list: @recipes_list %>

<%= link_to 'Back', recipes_lists_path %>

app/views/recipes_lists/show.html.erb
<div class="card-header d-flex justify-content-between">
  <div>
    <h5 class='m-0'>
      <b><%= @recipes_list.title %></b>
      <span class="badge badge-<%= @recipes_list.badge_color %>"><%= @recipes_list.status %></span>
    </h5>
    <p class='text-secondary m-0'><small><%= @recipes_list.percent_complete %>% complété (<%= @recipes_list.completed_items %>/<%= @recipes_list.total_items %> étapes)</small></p>
  </div>
  <div>
    <%= link_to 'Edit', edit_recipes_list_path(@recipes_list), class: 'btn btn-secondary' %>
  </div>
</div>

<div class="card-body">
  <div class="progress mb-4">
    <div class="progress-bar bg-info" role="progressbar" style="width: <%= @recipes_list.percent_complete %>%" aria-valuenow="<%= @recipes_list.percent_complete %>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>

  <%= form_for([@recipes_list, @todo_item]) do |f| %>
  <div class="input-group mb-4">
    <%= f.text_field :description, class: 'form-control', placeholder: 'Ajouter une étape' %>
    <div class="input-group-append">
      <% f.submit "Add", class: "btn btn-primary input-group-btn" %>
    </div>
  </div>
  <% end %>

  <ul class='list-group'>
  <% @recipes_list.todo_items.each do |todo_item| %>
    <% if todo_item.completed? %>
        <li class='list-group-item bg-light'>
        <div class="d-flex justify-content-between">
          <span class='text-muted'>
            <em><%= todo_item.description %></em>
          </span>
          <%= link_to '#', class: 'btn btn-dark', data: { reflex: 'click->TodoItem#mark_incomplete', id: todo_item.id } do %>
            <i class='fas fa-times'></i>
          <% end %>
        </div>
    </li>
    <% else %>
      <li class='list-group-item'>
          <div class="d-flex justify-content-between">
            <span>
              <%= todo_item.description %>
            </span>
            <%= link_to '#', class: 'btn btn-info', data: { reflex: 'click->TodoItem#mark_complete', id: todo_item.id } do %>
              <i class='fas fa-check'></i>
            <% end %>
          </div>
      </li>
    <% end %>
  <% end %>
  </ul>
</div>

app/views/todo_items/_form.html.erb
<%= form_with(model: [@todo_item.recipes_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :completed_at %><br />
    <%= f.datetime_select :completed_at %>
  </div>
  <div class="field">
    <%= f.label :recipes_list %><br />
    <%= f.text_field :recipes_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_item.recipes_list, @todo_item] %> |
<%= link_to 'Back', recipes_list_todo_items_path(@todo_item.recipes_list) %>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Completed</th>
    <th>Completed at</th>
    <th>Recipes list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.description %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.completed_at %></td>
    <td><%= todo_item.recipes_list %></td>
    <td><%= link_to 'Show', [todo_item.recipes_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_recipes_list_todo_item_path(todo_item.recipes_list, todo_item) %></td>
    <td><%= link_to 'Destroy', [todo_item.recipes_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_recipes_list_todo_item_path(params[:recipes_list_id]) %>

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_list_todo_items_path(@todo_item.recipes_list) %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @todo_item.description %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo_item.completed %>
</p>

<p>
  <b>Completed at:</b>
  <%= @todo_item.completed_at %>
</p>

<p>
  <b>Recipes list:</b>
  <%= @todo_item.recipes_list %>
</p>


<%= link_to 'Edit', edit_recipes_list_todo_item_path(@todo_item.recipes_list, @todo_item) %> |
<%= link_to 'Back', recipes_list_todo_items_path(@todo_item.recipes_list) %>